/*
 * Every article, newest first. Generated by `pnpm content` from content/pt-BR/articles: do not edit
 * by hand.
 */
import type { Frontmatter } from "./frontmatter";

export const articles: readonly (Frontmatter & { slug: string })[] = [
  {
    slug: "como-escrever-um-artigo",
    title: "Como escrever um artigo",
    description: "O que vai no topo de cada arquivo, onde ele mora e como ele chega ao site.",
    publishedAt: "2026-10-09",
    author: "Equipe",
  },
];
