import {
  type Choices,
  densities,
  type Elevation,
  elevations,
  type Face,
  knobs,
  motions,
  presets,
  shapes,
  type Temperature,
  temperatures,
  textSizes,
  typefaces,
} from "./preset-options";

/* What design.json resolves to, and the files the chosen knobs are written into. */

export type PresetName = keyof typeof presets;
export const presetNames = Object.keys(presets) as PresetName[];

export type Design = { preset: PresetName; choices: Choices };

/** Reads `preset` and `adjust` from design.json. Throws on any name that is not curated. */
export function parseDesign(value: unknown): Design {
  const input = (value ?? {}) as { preset?: unknown; adjust?: Record<string, unknown> };
  const preset = input.preset ?? "instrument";
  if (typeof preset !== "string" || !(preset in presets)) {
    throw new Error(`preset must be one of: ${presetNames.join(", ")}`);
  }
  const choices: Record<string, string> = { ...presets[preset as PresetName] };
  for (const [knob, option] of Object.entries(input.adjust ?? {})) {
    const options = (knobs as Record<string, readonly string[]>)[knob];
    if (options === undefined) {
      throw new Error(
        `adjust.${knob} is not a knob; the knobs are ${Object.keys(knobs).join(", ")}`,
      );
    }
    if (typeof option !== "string" || !options.includes(option)) {
      throw new Error(`adjust.${knob} must be one of: ${options.join(", ")}`);
    }
    choices[knob] = option;
  }
  return { preset: preset as PresetName, choices: choices as Choices };
}

export const temperatureOf = (choices: Choices): Temperature => temperatures[choices.temperature];
export const elevationOf = (choices: Choices): Elevation => elevations[choices.elevation];
export const isSerif = (choices: Choices): boolean => typefaces[choices.typeface].serif;

/** Every theme variable the chosen knobs set, in a fixed order so the output is stable. */
export function presetVariables(choices: Choices): [string, string][] {
  return Object.entries({
    ...typefaces[choices.typeface].vars,
    ...textSizes[choices.textSize],
    ...shapes[choices.shape],
    ...densities[choices.density],
    ...motions[choices.motion],
  });
}

const call = (role: string, face: Face) => {
  const extra = face.options === undefined ? "" : `\n  ${face.options},`;
  return `const ${role} = ${face.loader}({\n  variable: "--font-face-${role}",\n  subsets: ["latin"],${extra}\n});`;
};

/*
 * next/font reads its calls at compile time: each must be a literal call assigned to a module
 * level const, with literal options. So the module is written, not configured. When titles use
 * the text face there is no heading call, and the CSS falls back to the text face.
 */
export function renderFonts(choices: Choices): string {
  const face = typefaces[choices.typeface];
  const roles = (["heading", "sans", "mono"] as const).filter(
    (role) => role !== "heading" || face.heading.loader !== face.sans.loader,
  );
  const loaders = [...new Set(roles.map((role) => face[role].loader))].sort();
  return `/*
 * The faces of the "${choices.typeface}" typeface. Generated by \`pnpm tokens\` from design.json: do
 * not edit by hand.
 */
import { ${loaders.join(", ")} } from "next/font/google";

${roles.map((role) => call(role, face[role])).join("\n\n")}

/** The class names that declare the font variables; the root element carries them. */
export const fontVariables = [${roles.map((role) => `${role}.variable`).join(", ")}].join(" ");
`;
}

export function describeChoices(preset: PresetName, choices: Choices): [string, string][] {
  return [
    ["Preset", preset],
    ["Typeface", `${choices.typeface}: ${typefaces[choices.typeface].label}`],
    ["Text size", choices.textSize],
    ["Shape", choices.shape],
    ["Density", choices.density],
    ["Elevation", choices.elevation],
    ["Motion", choices.motion],
    ["Neutral temperature", choices.temperature],
    ["Contrast", choices.contrast],
  ];
}

/* The instrument values, in the order the theme file lists them. Each knob replaces some of them. */
const baseTheme: [string, string][] = [
  ["--text-display", "clamp(2.5rem, 1.6rem + 3vw, 3.5rem)"],
  ["--text-display--line-height", "1.07"],
  ["--text-display--letter-spacing", "-0.032em"],
  ["--text-display--font-weight", "700"],
  ["--text-page-title", "2rem"],
  ["--text-page-title--line-height", "2.375rem"],
  ["--text-page-title--letter-spacing", "-0.022em"],
  ["--text-page-title--font-weight", "650"],
  ["--text-section", "1.375rem"],
  ["--text-section--line-height", "1.75rem"],
  ["--text-section--letter-spacing", "-0.012em"],
  ["--text-section--font-weight", "600"],
  ["--text-block-title", "1.125rem"],
  ["--text-block-title--line-height", "1.5rem"],
  ["--text-block-title--letter-spacing", "-0.005em"],
  ["--text-block-title--font-weight", "600"],
  ["--text-body", "1.0625rem"],
  ["--text-body--line-height", "1.625rem"],
  ["--text-body-small", "0.9375rem"],
  ["--text-body-small--line-height", "1.375rem"],
  ["--text-field-label", "0.9375rem"],
  ["--text-field-label--line-height", "1.25rem"],
  ["--text-field-label--font-weight", "550"],
  ["--text-label", "0.875rem"],
  ["--text-label--line-height", "1.125rem"],
  ["--text-label--font-weight", "500"],
  ["--text-button", "1rem"],
  ["--text-button--line-height", "1.25rem"],
  ["--text-button--font-weight", "600"],
  ["--text-figure", "2.25rem"],
  ["--text-figure--line-height", "2.75rem"],
  ["--text-figure--letter-spacing", "-0.03em"],
  ["--text-figure--font-weight", "500"],
  ["--text-data", "0.9375rem"],
  ["--text-data--line-height", "1.375rem"],
  ...Object.entries(shapes.standard),
  ["--radius-full", "9999px"],
  // The rounded data end of a chart bar; the same in every preset, as the chart method asks.
  ["--radius-mark", "4px"],
  ["--spacing-control", "2.75rem"],
  ["--spacing-control-coarse", "3rem"],
  ["--spacing-field", "3rem"],
  ["--spacing-row", "3.5rem"],
  ["--spacing-chip", "2.25rem"],
  ["--spacing-segment", "2.5rem"],
  ["--spacing-bar", "3.75rem"],
  ["--spacing-tab", "4rem"],
  ["--spacing-sidebar", "15.5rem"],
  ["--spacing-panel-inset", "1.5rem"],
  ["--spacing-dialog-inset", "1.75rem"],
  ["--spacing-cell-x", "1rem"],
  ["--spacing-cell-y", "0.75rem"],
  ["--container-dialog", "32.5rem"],
  ...Object.entries(motions.calm).filter(([name]) => name.startsWith("--animate-")),
  ["--animate-spin", "spin 800ms linear infinite"],
  ["--ease-enter", motions.calm["--ease-enter"]],
  ["--ease-exit", "cubic-bezier(0.4, 0, 1, 1)"],
  ["--ease-move", "cubic-bezier(0.4, 0, 0.2, 1)"],
];

/*
 * The whole theme except color, for the chosen knobs. Tailwind's own scales are cleared first, so
 * only these names exist; spacing and breakpoints keep Tailwind's defaults plus the named sizes.
 */
export function renderPresetCss(preset: PresetName, choices: Choices): string {
  const face = typefaces[choices.typeface];
  const headingFallback = face.serif
    ? "ui-serif, Georgia, serif"
    : "ui-sans-serif, system-ui, sans-serif";
  const overrides = new Map(presetVariables(choices));
  const lines = baseTheme.map(([name, value]) => `  ${name}: ${overrides.get(name) ?? value};`);
  return `/*
 * Type, shape, density and motion of the "${preset}" preset. Generated by \`pnpm tokens\` from
 * design.json: do not edit by hand.
 */

@theme {
  --font-*: initial;
  --text-*: initial;
  --radius-*: initial;
  --inset-shadow-*: initial;
  --drop-shadow-*: initial;
  --text-shadow-*: initial;
  --blur-*: initial;
  --animate-*: initial;
  --ease-*: initial;

  --font-heading:
    var(--font-face-heading, var(--font-face-sans)), ${headingFallback};
  --font-sans: var(--font-face-sans), ui-sans-serif, system-ui, sans-serif;
  --font-mono: var(--font-face-mono), ui-monospace, monospace;

${lines.join("\n")}
}
`;
}
