import { css, hex, type PairReport, type Palette, type TokenName, tokenNames } from "./generate";

/* Turns generated palettes into the text of each file the generator owns. */

const SCRIM = "oklch(0% 0 0 / 0.5)";
const SHADOW_OPACITY = 0.28;

const declarations = (palette: Palette, indent: string) =>
  tokenNames.map((name) => `${indent}--color-${name}: ${css(palette[name])};`).join("\n");

export function renderTokensCss(light: Palette, dark: Palette): string {
  const lightShadow = `0 1px 0 var(--color-line), 0 16px 40px -16px ${css(light.ink, SHADOW_OPACITY)}`;
  const darkShadow = "0 0 0 1px var(--color-line-strong)";
  return `/*
 * Color tokens. Every color in the interface comes from this file.
 * Generated by \`pnpm tokens\` from colors.json: do not edit by hand.
 */

@theme {
  --color-*: initial;

${declarations(light, "  ")}
  --color-scrim: ${SCRIM};

  --shadow-*: initial;
  --shadow-layer: ${lightShadow};
}

@layer base {
  :root {
    color-scheme: light;
  }

  :root[data-theme="dark"] {
    color-scheme: dark;
${declarations(dark, "    ")}
    --shadow-layer: ${darkShadow};
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      color-scheme: dark;
${declarations(dark, "      ")}
      --shadow-layer: ${darkShadow};
    }
  }
}
`;
}

const emailKeys: ReadonlyArray<readonly [string, TokenName]> = [
  ["background", "background"],
  ["surface", "surface"],
  ["line", "line"],
  ["ink", "ink"],
  ["inkMuted", "ink-muted"],
  ["action", "action"],
  ["onAction", "on-action"],
  ["brandInk", "brand-ink"],
];

export function renderEmailPalette(light: Palette): string {
  const lines = emailKeys.map(([key, token]) => `  ${key}: "${hex(light[token])}",`).join("\n");
  return `/*
 * E-mail clients understand neither CSS variables nor oklch, so e-mails use these sRGB values of
 * the light theme tokens. Generated by \`pnpm tokens\` from colors.json: do not edit by hand.
 */
export const emailPalette = {
${lines}
} as const;
`;
}

/** The light theme as the YAML lines of the DESIGN.md frontmatter. */
export function renderFrontmatterColors(light: Palette): string {
  return tokenNames.map((name) => `  ${name}: "${css(light[name])}"`).join("\n");
}

export function renderDesignTables(
  light: Palette,
  dark: Palette,
  report: readonly PairReport[],
): string {
  const rows = tokenNames.map(
    (name) => `| \`${name}\` | \`${css(light[name])}\` | \`${css(dark[name])}\` |`,
  );
  const pairs = report
    .map(
      ({ theme, foreground, background, ratio, minimum }) =>
        `| ${theme} | \`${foreground}\` on \`${background}\` | ${ratio.toFixed(1)}:1 | ${minimum}:1 |`,
    )
    .join("\n");
  return `| Token | Light | Dark |
|-------|-------|------|
${rows.join("\n")}

| Theme | Pair | Measured | Needs |
|-------|------|----------|-------|
${pairs}`;
}

/** Replaces the text between two marker lines, keeping the markers. */
export function replaceBetween(text: string, start: string, end: string, body: string): string {
  const from = text.indexOf(start);
  const to = text.indexOf(end);
  if (from === -1 || to === -1 || to < from) {
    throw new Error(`Markers not found: ${start} ... ${end}`);
  }
  return `${text.slice(0, from + start.length)}\n${body}\n${text.slice(to)}`;
}
