import { type AccentPalette, type AccentReport, accentTokenNames } from "./accent";
import type { DataPalette } from "./data";
import { css, hex, type PairReport, type Palette, type TokenName, tokenNames } from "./generate";
import type { PaletteColor } from "./palettes";
import type { Elevation } from "./preset-options";

export type RenderedAccent = { name: string; light: AccentPalette; dark: AccentPalette };

/* Turns generated palettes into the text of each file the generator owns. */

const SCRIM = "oklch(0% 0 0 / 0.5)";

const declarations = (palette: Palette, indent: string) =>
  tokenNames.map((name) => `${indent}--color-${name}: ${css(palette[name])};`).join("\n");

const accentDeclarations = (palette: AccentPalette, indent: string) =>
  accentTokenNames.map((name) => `${indent}--color-${name}: ${css(palette[name])};`).join("\n");

/*
 * Each accent redefines its four variables on its container. The dark rules carry the theme
 * selector in front, so they outrank the light rule on the same element, and a nested container
 * wins over its parent because its own declaration beats the inherited value.
 */
function renderAccentScopes(accents: readonly RenderedAccent[]): string {
  const scope = (name: string) => `[data-accent="${name}"]`;
  const rules = (selector: (name: string) => string, theme: "light" | "dark", indent: string) =>
    accents
      .map(
        (a) =>
          `${indent}${selector(a.name)} {\n${accentDeclarations(a[theme], `${indent}  `)}\n${indent}}`,
      )
      .join("\n\n");
  return `
@layer base {
${rules(scope, "light", "  ")}

${rules((name) => `:root[data-theme="dark"] ${scope(name)}`, "dark", "  ")}

  @media (prefers-color-scheme: dark) {
${rules((name) => `:root:not([data-theme="light"]) ${scope(name)}`, "dark", "    ")}
  }
}
`;
}

/** The brand comes first: it is the accent outside every scope and the way back to it inside one. */
const dataDeclarations = (palette: DataPalette, indent: string) =>
  palette.map(([name, color]) => `${indent}--color-${name}: ${css(color)};`).join("\n");

const paletteDeclarations = (colors: readonly PaletteColor[], indent: string) =>
  colors
    .map(
      ({ group, name, fill, ink }) =>
        `${indent}--color-${group}-${name}: ${css(fill)};\n${indent}--color-${group}-${name}-ink: ${css(ink)};`,
    )
    .join("\n");

/**
 * What a person's choice of stronger contrast changes. Only the roles the reinforced palette moves
 * are written, so the rule stays short, and it wins over the theme's own block by one more
 * attribute in the selector. The accent scopes keep their own colors.
 */
export type ContrastOverlay = { light: Palette; dark: Palette };

/** The roles the reinforced palette moves in either theme. Each theme restates all of them. */
const moved = (base: { light: Palette; dark: Palette }, stronger: ContrastOverlay) =>
  tokenNames.filter(
    (name) =>
      css(base.light[name]) !== css(stronger.light[name]) ||
      css(base.dark[name]) !== css(stronger.dark[name]),
  );

/*
 * Both themes list the same roles. If only the one that moved were written, the light rule, which
 * is as specific as the dark theme's own block, would paint light colors over a dark page.
 */
export function renderContrastOverlay(
  base: { light: Palette; dark: Palette },
  stronger: ContrastOverlay,
): string {
  const names = moved(base, stronger);
  if (names.length === 0) {
    return "";
  }
  const lines = (palette: Palette, indent: string) =>
    names.map((name) => `${indent}--color-${name}: ${css(palette[name])};`).join("\n");
  return `
@layer base {
  :root[data-contrast="more"] {
${lines(stronger.light, "    ")}
  }

  :root[data-theme="dark"][data-contrast="more"] {
${lines(stronger.dark, "    ")}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"])[data-contrast="more"] {
${lines(stronger.dark, "      ")}
    }
  }
}
`;
}

export type ThemePalettes = {
  light: Palette;
  dark: Palette;
  data: { light: DataPalette; dark: DataPalette };
  palettes: { light: PaletteColor[]; dark: PaletteColor[] };
};

export function renderTokensCss(
  { light, dark, data, palettes }: ThemePalettes,
  accents: readonly [RenderedAccent, ...RenderedAccent[]],
  elevation: Elevation,
  stronger: ContrastOverlay | null,
): string {
  const [brand] = accents;
  const { rim, offset, blur, spread, opacity } = elevation;
  const lightShadow = `${rim} var(--color-line), 0 ${offset} ${blur} ${spread} ${css(light.ink, opacity)}`;
  const darkShadow = "0 0 0 1px var(--color-line-strong)";
  return `/*
 * Color tokens. Every color in the interface comes from this file.
 * Generated by \`pnpm tokens\` from design.json: do not edit by hand.
 */

@theme {
  --color-*: initial;

${declarations(light, "  ")}
${accentDeclarations(brand.light, "  ")}
${dataDeclarations(data.light, "  ")}
${paletteDeclarations(palettes.light, "  ")}
  --color-scrim: ${SCRIM};

  --shadow-*: initial;
  --shadow-layer: ${lightShadow};
}

@layer base {
  :root {
    color-scheme: light;
  }

  :root[data-theme="dark"] {
    color-scheme: dark;
${declarations(dark, "    ")}
${accentDeclarations(brand.dark, "    ")}
${dataDeclarations(data.dark, "    ")}
${paletteDeclarations(palettes.dark, "    ")}
    --shadow-layer: ${darkShadow};
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      color-scheme: dark;
${declarations(dark, "      ")}
${accentDeclarations(brand.dark, "      ")}
${dataDeclarations(data.dark, "      ")}
${paletteDeclarations(palettes.dark, "      ")}
      --shadow-layer: ${darkShadow};
    }
  }
}
${stronger === null ? "" : renderContrastOverlay({ light, dark }, stronger)}${renderAccentScopes(accents)}`;
}

const LINE_WIDTH = 100;
const PLAIN_KEY = /^[a-z][a-z0-9]*$/;

/** The domain palettes as a module, so code and the catalog know the groups and their colors. */
export function renderPaletteNames(colors: readonly PaletteColor[]): string {
  const groups = new Map<string, string[]>();
  for (const { group, name } of colors) {
    groups.set(group, [...(groups.get(group) ?? []), name]);
  }
  const key = (group: string) => (PLAIN_KEY.test(group) ? group : JSON.stringify(group));
  const entry = (group: string, names: readonly string[]) => {
    const quoted = names.map((name) => JSON.stringify(name));
    const inline = `  ${key(group)}: [${quoted.join(", ")}],`;
    return inline.length <= LINE_WIDTH
      ? inline
      : `  ${key(group)}: [\n${quoted.map((q) => `    ${q},`).join("\n")}\n  ],`;
  };
  const body = [...groups].map(([group, names]) => entry(group, names)).join("\n");
  return `/*
 * The named palettes a product declares in design.json. Generated by \`pnpm tokens\`: do not edit by
 * hand. Each color is a pair of tokens, \`<group>-<name>\` for marks and \`<group>-<name>-ink\` for text.
 */
export const paletteNames = {
${body}
} as const;
`;
}

/** The accent names as a module, so code and the catalog know which scopes exist. */
export function renderAccentNames(names: readonly string[]): string {
  const quoted = names.map((name) => `"${name}"`);
  const inline = `export const accentNames = [${quoted.join(", ")}] as const;`;
  const list =
    inline.length <= LINE_WIDTH
      ? inline
      : `export const accentNames = [\n${quoted.map((q) => `  ${q},`).join("\n")}\n] as const;`;
  return `/*
 * The scoped accents a container can name with data-accent. Generated by \`pnpm tokens\` from
 * colors.json: do not edit by hand.
 */
${list}

export type AccentName = (typeof accentNames)[number];
`;
}

const emailKeys: ReadonlyArray<readonly [string, TokenName]> = [
  ["background", "background"],
  ["surface", "surface"],
  ["line", "line"],
  ["ink", "ink"],
  ["inkMuted", "ink-muted"],
  ["action", "action"],
  ["onAction", "on-action"],
  ["brandInk", "brand-ink"],
];

export function renderEmailPalette(light: Palette): string {
  const lines = emailKeys.map(([key, token]) => `  ${key}: "${hex(light[token])}",`).join("\n");
  return `/*
 * E-mail clients understand neither CSS variables nor oklch, so e-mails use these sRGB values of
 * the light theme tokens. Generated by \`pnpm tokens\` from design.json: do not edit by hand.
 */
export const emailPalette = {
${lines}
} as const;
`;
}

/** The light theme as the YAML lines of the DESIGN.md frontmatter. */
export function renderFrontmatterColors(light: Palette): string {
  return tokenNames.map((name) => `  ${name}: "${css(light[name])}"`).join("\n");
}

/*
 * One row per accent and theme, with the lowest ratio of each check, so the table stays short as
 * accents are added. The generator already refused anything below the minimum.
 */
function renderAccentTables(accents: readonly RenderedAccent[], report: readonly AccentReport[]) {
  const values = accents.flatMap((a) =>
    accentTokenNames.map(
      (token) =>
        `| ${a.name} | \`${token}\` | \`${css(a.light[token])}\` | \`${css(a.dark[token])}\` |`,
    ),
  );
  const lowest = (rows: readonly AccentReport[], foreground: string, against?: string) =>
    Math.min(
      ...rows
        .filter(
          (r) => r.foreground === foreground && (against === undefined || r.background === against),
        )
        .map((r) => r.ratio),
    ).toFixed(1);
  const checks = accents.flatMap((a) =>
    (["light", "dark"] as const).map((theme) => {
      const rows = report.filter((r) => r.accent === a.name && r.theme === theme);
      return `| ${a.name} | ${theme} | ${lowest(rows, "accent", "surface")}:1 | ${lowest(rows, "on-accent")}:1 | ${lowest(rows, "accent-ink")}:1 |`;
    }),
  );
  return `| Accent | Token | Light | Dark |
|--------|-------|-------|------|
${values.join("\n")}

| Accent | Theme | Fill on surface (3:1) | Text on fill (4.5:1) | Ink, lowest (4.5:1) |
|--------|-------|-----------------------|----------------------|---------------------|
${checks.join("\n")}`;
}

export function renderDesignTables(
  { light, dark, report }: { light: Palette; dark: Palette; report: readonly PairReport[] },
  scoped: { accents: readonly RenderedAccent[]; report: readonly AccentReport[] },
): string {
  const rows = tokenNames.map(
    (name) => `| \`${name}\` | \`${css(light[name])}\` | \`${css(dark[name])}\` |`,
  );
  const pairs = report
    .map(
      ({ theme, foreground, background, ratio, minimum }) =>
        `| ${theme} | \`${foreground}\` on \`${background}\` | ${ratio.toFixed(1)}:1 | ${minimum}:1 |`,
    )
    .join("\n");
  return `| Token | Light | Dark |
|-------|-------|------|
${rows.join("\n")}

| Theme | Pair | Measured | Needs |
|-------|------|----------|-------|
${pairs}

${renderAccentTables(scoped.accents, scoped.report)}`;
}

/** Replaces the text between two marker lines, keeping the markers. */
export function replaceBetween(text: string, start: string, end: string, body: string): string {
  const from = text.indexOf(start);
  const to = text.indexOf(end);
  if (from === -1 || to === -1 || to < from) {
    throw new Error(`Markers not found: ${start} ... ${end}`);
  }
  return `${text.slice(0, from + start.length)}\n${body}\n${text.slice(to)}`;
}

/** The chosen knobs and every variable they set, for the Preset section of DESIGN.md. */
export function renderPresetTables(
  choices: readonly [string, string][],
  variables: readonly [string, string][],
): string {
  const knobRows = choices.map(([knob, value]) => `| ${knob} | ${value} |`);
  const variableRows =
    variables.length === 0
      ? ["| (none) | the instrument values in this file apply unchanged |"]
      : variables.map(([name, value]) => `| \`${name}\` | \`${value}\` |`);
  return `| Knob | Choice |
|------|--------|
${knobRows.join("\n")}

| Variable the preset sets | Value |
|--------------------------|-------|
${variableRows.join("\n")}`;
}
