/*
 * The faces of the "instrument" typeface. Generated by `pnpm tokens` from design.json: do
 * not edit by hand.
 */
import { JetBrains_Mono, Onest } from "next/font/google";

const sans = Onest({
  variable: "--font-face-sans",
  subsets: ["latin"],
});

const mono = JetBrains_Mono({
  variable: "--font-face-mono",
  subsets: ["latin"],
});

/** The class names that declare the font variables; the root element carries them. */
export const fontVariables = [sans.variable, mono.variable].join(" ");
