/*
 * The scoped accents a container can name with data-accent. Generated by `pnpm tokens` from
 * colors.json: do not edit by hand.
 */
export const accentNames = ["brand", "coral", "teal", "plum"] as const;

export type AccentName = (typeof accentNames)[number];
