/*
 * The named palettes a product declares in design.json. Generated by `pnpm tokens`: do not edit by
 * hand. Each color is a pair of tokens, `<group>-<name>` for marks and `<group>-<name>-ink` for text.
 */
export const paletteNames = {
  category: ["alpha", "beta", "gamma", "delta", "epsilon"],
} as const;
