export type StoredFile = { body: Uint8Array<ArrayBuffer>; contentType: string };

/*
 * The shape every file destination implements. Every file is private: the only way to read one
 * from a browser is a signed URL that expires. Downloads are always attachments, never rendered
 * on the app's own origin.
 */
export type FileStorage = {
  put: (key: string, file: StoredFile) => Promise<void>;
  /** The file's bytes, for the account export. Null when there is no such file. */
  get: (key: string) => Promise<StoredFile | null>;
  remove: (key: string) => Promise<void>;
  signedUrl: (
    key: string,
    options: { expiresInSeconds: number; downloadName: string },
  ) => Promise<string>;
};

/** Keys are generated by the app; this rejects anything that could escape the storage root. */
const safeKey = /^[a-z0-9][a-z0-9_-]*(?:\/[a-z0-9][a-z0-9._-]*)*$/;

export function assertSafeKey(key: string): void {
  if (!safeKey.test(key) || key.includes("..")) {
    throw new Error("Unsafe storage key");
  }
}
