import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { parse } from "yaml";
import { frontmatterSchema } from "../lib/content/frontmatter";
import { z } from "../lib/validation";

/*
 * `pnpm content` reads every article, checks its frontmatter and its text, and writes the index the
 * app reads: the list page, the sitemap and the proxy's 404 all come from it, so production never
 * lists the content folder. `--check` only compares, which is what `pnpm check` runs. Text a person
 * reads follows the catalog rule: no em dash, written or as an entity, frontmatter included.
 */

const root = path.resolve(import.meta.dirname, "..");
const folder = path.join(root, "content", "pt-BR", "articles");
const output = path.join(root, "lib", "content", "articles-index.ts");
const forbidden = /—|&mdash;|&#8212;|&#x2014;/giu;
const slugShape = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const frontmatterBlock = /^---\n([\s\S]*?)\n---\n/;

const problems: string[] = [];
const files = readdirSync(folder)
  .filter((file) => file.endsWith(".mdx"))
  .sort();

const articles = files.flatMap((file) => {
  const where = path.relative(root, path.join(folder, file));
  const text = readFileSync(path.join(folder, file), "utf8");
  for (const [index, line] of text.split("\n").entries()) {
    for (const match of line.matchAll(forbidden)) {
      problems.push(`${where}:${index + 1}:${(match.index ?? 0) + 1}: em dash in content`);
    }
  }
  const slug = file.slice(0, -".mdx".length);
  if (!slugShape.test(slug)) {
    problems.push(`${where}: the file name must be lowercase words joined by hyphens`);
    return [];
  }
  const block = frontmatterBlock.exec(text)?.[1];
  const parsed = frontmatterSchema.safeParse(block === undefined ? undefined : parse(block));
  if (!parsed.success) {
    problems.push(`${where}: invalid frontmatter\n${z.prettifyError(parsed.error)}`);
    return [];
  }
  return [{ slug, ...parsed.data }];
});

if (problems.length > 0) {
  process.stderr.write(`${problems.join("\n")}\n`);
  process.exit(1);
}

/* Written the way the formatter writes it, so the check compares like with like. */
function renderList(items: readonly Record<string, string | undefined>[]): string {
  if (items.length === 0) {
    return "[]";
  }
  const objects = items.map((item) => {
    const fields = Object.entries(item)
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},`);
    return `  {\n${fields.join("\n")}\n  },`;
  });
  return `[\n${objects.join("\n")}\n]`;
}

// Newest first, so the list and the sitemap read in the order people expect.
articles.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt) || a.slug.localeCompare(b.slug));
const content = `/*
 * Every article, newest first. Generated by \`pnpm content\` from content/pt-BR/articles: do not edit
 * by hand.
 */
import type { Frontmatter } from "./frontmatter";

export const articles: readonly (Frontmatter & { slug: string })[] = ${renderList(articles)};
`;

const current = (() => {
  try {
    return readFileSync(output, "utf8");
  } catch {
    return "";
  }
})();
if (process.argv.includes("--check")) {
  if (current !== content) {
    process.stderr.write("The article index is out of date. Run `pnpm content`.\n");
    process.exit(1);
  }
} else if (current !== content) {
  writeFileSync(output, content);
  process.stdout.write(`wrote ${path.relative(root, output)}\n`);
}
