import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import { createTranslator } from "next-intl";
import { parse, YAMLParseError } from "yaml";
import { frontmatterSchema } from "../lib/content/frontmatter";
import {
  badSlug,
  emDash,
  frontmatterProblems,
  invalidYaml,
  missingBlock,
  type Translate,
} from "../lib/content/problems";
import messages from "../messages/pt-BR.json";

/*
 * `pnpm content` reads every article, checks its frontmatter and its text, and writes the index the
 * app reads: the list page, the sitemap and the proxy's 404 all come from it, so production never
 * lists the content folder. `--check` only compares, which is what `pnpm check` runs. Text a person
 * reads follows the catalog rule: no em dash, written or as an entity, frontmatter included.
 */

const root = path.resolve(import.meta.dirname, "..");
const folder = path.join(root, "content", "pt-BR", "articles");
const output = path.join(root, "lib", "content", "articles-index.ts");
const forbidden = /—|&mdash;|&#8212;|&#x2014;/giu;
const slugShape = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const frontmatterBlock = /^---\n([\s\S]*?)\n---\n/;

// What this prints is for a person writing an article, so it is read from the catalog like any text.
const translator = createTranslator({ locale: "pt-BR", messages });
const t: Translate = (key, values) =>
  (translator as unknown as (key: string, values?: Record<string, string | number>) => string)(
    key,
    values,
  );

const problems: string[] = [];
const files = readdirSync(folder)
  .filter((file) => file.endsWith(".mdx"))
  .sort();

const articles = files.flatMap((file) => {
  const where = path.relative(root, path.join(folder, file));
  const text = readFileSync(path.join(folder, file), "utf8");
  for (const [index, line] of text.split("\n").entries()) {
    for (const match of line.matchAll(forbidden)) {
      problems.push(emDash(where, index + 1, (match.index ?? 0) + 1, t));
    }
  }
  const slug = file.slice(0, -".mdx".length);
  if (!slugShape.test(slug)) {
    problems.push(badSlug(where, t));
    return [];
  }
  const block = frontmatterBlock.exec(text)?.[1];
  if (block === undefined) {
    problems.push(missingBlock(where, t));
    return [];
  }
  let data: unknown;
  try {
    data = parse(block);
  } catch (error) {
    const detail = error instanceof YAMLParseError ? error.message.split("\n")[0] : String(error);
    problems.push(invalidYaml(where, detail ?? "", t));
    return [];
  }
  const parsed = frontmatterSchema.safeParse(data);
  if (!parsed.success) {
    problems.push(...frontmatterProblems(where, parsed.error, t));
    return [];
  }
  return [{ slug, ...parsed.data }];
});

if (problems.length > 0) {
  process.stderr.write(`${problems.join("\n")}\n`);
  process.exit(1);
}

/* Written the way the formatter writes it, so the check compares like with like. */
function renderList(items: readonly Record<string, string | undefined>[]): string {
  if (items.length === 0) {
    return "[]";
  }
  const objects = items.map((item) => {
    const fields = Object.entries(item)
      .filter(([, value]) => value !== undefined)
      .map(([key, value]) => `    ${key}: ${JSON.stringify(value)},`);
    return `  {\n${fields.join("\n")}\n  },`;
  });
  return `[\n${objects.join("\n")}\n]`;
}

// Newest first, so the list and the sitemap read in the order people expect.
articles.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt) || a.slug.localeCompare(b.slug));
const content = `/*
 * Every article, newest first. Generated by \`pnpm content\` from content/pt-BR/articles: do not edit
 * by hand.
 */
import type { Frontmatter } from "./frontmatter";

export const articles: readonly (Frontmatter & { slug: string })[] = ${renderList(articles)};
`;

const current = (() => {
  try {
    return readFileSync(output, "utf8");
  } catch {
    return "";
  }
})();
if (process.argv.includes("--check")) {
  if (current !== content) {
    process.stderr.write("The article index is out of date. Run `pnpm content`.\n");
    process.exit(1);
  }
} else if (current !== content) {
  writeFileSync(output, content);
  process.stdout.write(`wrote ${path.relative(root, output)}\n`);
}
