/*
 * E-mail clients understand neither CSS variables nor oklch, so e-mails use these sRGB values of
 * the light theme tokens. Generated by `pnpm tokens` from design.json: do not edit by hand.
 */
export const emailPalette = {
  background: "#f3f6fa",
  surface: "#fcfeff",
  line: "#ced5dc",
  ink: "#131e28",
  inkMuted: "#4c5760",
  action: "#131e28",
  onAction: "#fcfeff",
  brandInk: "#00578b",
} as const;
